In [65]:
import numpy as np

In [76]:
actions = np.array([0.37143266, 0.15378678, 0.46550912, 0.15805447, 0.06253012, 0.90064555,
 0.        , 0.654408,   0.26650083 ,0.         ,0.29430538 ,0.13390543,
 0.701032  , 0.7477346 , 0.       ,  1.   ,      0.7793279 , 0.8416198,
 0.19586198, 0.2867668 , 0.      ,   0.     ,    0.570027  , 0.,
 0.3929516 , 0.      ,   0.11664659 ,0.        ])

In [70]:
actions = np.array([0, 1, 0, 1, 0, 0])

In [71]:
actions

array([0, 1, 0, 1, 0, 0])

In [72]:
def normalize_action_vector(action_vector):
    # Find the maximum value in the action vector
    max_value = np.max(action_vector)

    # Set elements less than 5% of the max value to 0
    action_vector = np.where(action_vector >= 0.05 * max_value, action_vector, 0)

    # Calculate the sum of the non-zero elements
    non_zero_sum = np.sum(action_vector)

    # Avoid division by zero
    if non_zero_sum == 0:
        return action_vector

    # Normalize non-zero elements while maintaining their ratio and adjusting to the max value
    normalized_action_vector = action_vector / non_zero_sum * max_value

    return normalized_action_vector


def bin_action_values(action_vector):
    # Define the bin edges
    bins = np.arange(0, 1.1, 0.1)  # Creates an array [0.0, 0.1, 0.2, ..., 1.0]

    # Reshape action_vector for broadcasting
    action_vector_reshaped = action_vector.reshape(-1, 1)

    # Calculate the absolute differences between each action value and bin edge
    abs_diff = np.abs(action_vector_reshaped - bins)

    # Find the indices of the closest bin edge for each action value
    closest_bin_indices = np.argmin(abs_diff, axis=1)

    # Assign the closest bin value
    binned_action_vector = bins[closest_bin_indices]

    return binned_action_vector

In [78]:
actions = normalize_action_vector(actions)
actions

array([0.04301075, 0.02150538, 0.05376344, 0.02150538, 0.01075269,
       0.09677419, 0.        , 0.07526882, 0.03225806, 0.        ,
       0.03225806, 0.01075269, 0.07526882, 0.07526882, 0.        ,
       0.10752688, 0.08602151, 0.08602151, 0.02150538, 0.03225806,
       0.        , 0.        , 0.06451613, 0.        , 0.04301075,
       0.        , 0.01075269, 0.        ])

In [77]:
actions = bin_action_values(actions)
actions

array([0.4, 0.2, 0.5, 0.2, 0.1, 0.9, 0. , 0.7, 0.3, 0. , 0.3, 0.1, 0.7,
       0.7, 0. , 1. , 0.8, 0.8, 0.2, 0.3, 0. , 0. , 0.6, 0. , 0.4, 0. ,
       0.1, 0. ])